In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('customer.csv')

In [ ]:
df.sample(5)

    age  gender   review education purchased
0    30  Female  Average    School        No
37   94    Male  Average        PG       Yes
12   51    Male     Poor    School        No
18   19    Male     Good    School        No
20   57  Female  Average    School       Yes

In [ ]:
df = df.iloc[:,2:]

In [ ]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 0:2], df.iloc[:, -1], test_size=0.2)

In [ ]:
x_train

array([[2., 2.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [2., 2.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [1., 2.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 0.],
       [2., 2.],
       [1., 2.],
       [2., 1.]])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
os = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
os.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
x_train = os.transform(x_train)
x_test = os.transform(x_test)

In [ ]:
os.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)